@startuml VoiceParrotingSequence
participant MainPage
participant StartButton
participant VoiceParrotingService as Service
StartButton -> Service : Service Request
Service -> VoiceRecorder : Initialize Request
Service -> VoicePlayer : Initialize Request

VoiceRecorder --> Service : Initialize Response
VoicePlayer --> Service : Initialize Response

Service -> VoiceRecorder : Start
activate VoiceRecorder

Service -> Service : Wait for the delay timer ends

Service -> VoicePlayer : Start
activate VoicePlayer

... ...

VoiceRecorder --> Service 
deactivate VoiceRecorder

VoicePlayer --> Service
deactivate VoicePlayer

Service -> VoiceRecorder : Finalize
Service -> VoicePlayer : Finalize

Service --> MainPage 

@enduml